[package]
name = "blc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The Baseline programming language compiler"

[dependencies]
clap = { version = "4", features = ["derive"] }
tree-sitter.workspace = true
tree-sitter-baseline = { path = "../tree-sitter-baseline" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
