[package]
name = "blc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The Baseline programming language compiler"

[lib]
name = "blc"
path = "src/lib.rs"

[[bin]]
name = "blc"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tree-sitter.workspace = true
tree-sitter-baseline = { path = "../tree-sitter-baseline" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
